"""Metric definitions for performance and behavior analysis."""

from .metrics import (
    METRIC_DEFINITIONS,
    MetricCategory,
    MetricDefinition,
    MetricStatus,
)
from .portfolio import (
    PortfolioAnalysis,
    PortfolioSummary,
    PortfolioTokenPosition,
    PositionClassification,
    PositionLifecycle,
    analyze_normalized_portfolio,
    analyze_portfolio,
)
from .performance import (
    ClosedTradePerformance,
    PnlDistributionBucket,
    TradePerformanceAnalysis,
    TradePerformanceSummary,
    analyze_fifo_pipeline_performance,
    analyze_fifo_trade_performance,
    build_closed_trade_performance_rows,
    summarize_closed_trade_performance,
)
from .trade_diagnostics import (
    MatchedTradeDiagnostic,
    TokenPnlDiagnostic,
    TradeDiagnosticReport,
    TradeDiagnosticSummary,
    build_trade_diagnostic_report,
    summarize_trade_diagnostic_report,
)
from .wallet_behavior import (
    BehaviorTradeRow,
    ConcentrationDiagnostics,
    CostBasisBucketDiagnostic,
    DailyBehaviorDiagnostic,
    FastRotationDiagnostic,
    HoldingTimeBucketDiagnostic,
    NotionalDiagnostics,
    StreakDiagnostics,
    TokenConcentrationDiagnostic,
    WalletBehaviorReport,
    WalletBehaviorSummary,
    build_wallet_behavior_report,
    summarize_wallet_behavior,
)

__all__ = [
    "ClosedTradePerformance",
    "METRIC_DEFINITIONS",
    "MetricCategory",
    "MetricDefinition",
    "MetricStatus",
    "PortfolioAnalysis",
    "PortfolioSummary",
    "PortfolioTokenPosition",
    "PositionClassification",
    "PositionLifecycle",
    "PnlDistributionBucket",
    "TradePerformanceAnalysis",
    "TradePerformanceSummary",
    "analyze_normalized_portfolio",
    "analyze_portfolio",
    "analyze_fifo_pipeline_performance",
    "analyze_fifo_trade_performance",
    "build_closed_trade_performance_rows",
    "summarize_closed_trade_performance",
    "MatchedTradeDiagnostic",
    "TokenPnlDiagnostic",
    "TradeDiagnosticReport",
    "TradeDiagnosticSummary",
    "build_trade_diagnostic_report",
    "summarize_trade_diagnostic_report",
    "BehaviorTradeRow",
    "ConcentrationDiagnostics",
    "CostBasisBucketDiagnostic",
    "DailyBehaviorDiagnostic",
    "FastRotationDiagnostic",
    "HoldingTimeBucketDiagnostic",
    "NotionalDiagnostics",
    "StreakDiagnostics",
    "TokenConcentrationDiagnostic",
    "WalletBehaviorReport",
    "WalletBehaviorSummary",
    "build_wallet_behavior_report",
    "summarize_wallet_behavior",
]
